# This is a basic workflow to help you get started with Actions

name: Production Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #- name: Install Composer Dependencies
      #  run: composer install --prefer-dist --no-progress

      #- name: npm install
      #  run: npm install

      #- name: npm run bundle
      #  run: npm run bundle

      - name: FTP Deploy to WP Engine (Production)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.lz1haa.eu:21/
          ftp-username: webuploadingneuqzvimiat@lz1haa.eu
          ftp-password: ${{ secrets.PROD_FTP_PASSWORD }}
          local-dir: ../../releases/tag/2.0.0/
