# This is a basic workflow to help you get started with Actions

name: 🚀 HTTP Deploy release binary to firmare update server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #- name: Install Composer Dependencies
      #  run: composer install --prefer-dist --no-progress

      #- name: npm install
      #  run: npm install

      #- name: npm run bundle
      #  run: npm run bundle
      
      - name: Download release asset
        uses: robinraju/release-downloader@v1.6
        with:
          latest: true
          fileName: "WOLF-RA8875_GT911.bin"
          
      - run: pwd && ls -la

      - name: Send HTTP Form-Data POST Request
        uses: alikamal1/Form_Data_HTTP_POST_Action@main
        with:
          url: 'https://lz1haa.eu/wolf/trx_services/post_fw.php'
          headers: '{"Origin": "https://lz1haa.eu", "x-api-key": "123456"}'
          data: '{"fileType": "stm", "fileVersion": "99.99.99"}'
          name: 'uploadedFile'
          file: './WOLF-RA8875_GT911.bin'
